config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  get "/managed_projects" => "projects#managed_projects"
  get "/contributed_projects" => "projects#contributed_projects"

  resources :notifications, only: [:index] do
    member do
      put "mark_as_read"
    end
  end

  authenticated :user do
    root "users#dashboard"
  end

  get "/users/search" => "users#search"

  resources :projects do
    post "/create" => "user_projects#create"
    delete "/destroy" => "user_projects#destroy"
    get "/participants" => "user_projects#participants"
    member do
      get "link_contributors"
    end
    collection do
      get "managed"
      get "contributed"
    end
    resources :tasks
    post "/tasks/:id/assign" => "user_tasks#assign"
    delete "/tasks/:id/leave" => "user_tasks#leave"
    put "/tasks/:id/done" => "tasks#mark_as_done"
    resources :events
  end

  root "home#index"
end

app/models/task.rb
class Task < ApplicationRecord
  include NotificationMethods

  validates :title, :description, :due_date, presence: true
  validates :due_date, future_date: true

  has_many :user_tasks, dependent: :destroy
  has_many :participants, through: :user_tasks, source: :user

  has_many :notifications, as: :notificable

  belongs_to :project

  scope :projects_with_not_done_tasks, -> { not_done.group_by(&:project) }
  scope :not_done, -> { where(done: false) }
  scope :done, -> { where(done: true) }

  def projects_contributors
    project.contributors
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, except: [:new, :create, :index]
  before_action { authorize @project, :access? }

  def show
  end

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save_and_notify(current_user, :projects_contributors)
      redirect_to [@project, @task], notice: "Task was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update_and_notify(task_params, current_user, :participants)
      redirect_to [@project, @task], notice: "Task was successfully updated."
    else
      render :edit
    end
  end

  def mark_as_done
    respond_to do |format|
      if @task.update_and_notify({ done: true }, current_user, :participants)
        format.html { redirect_to project_tasks_path, notice: "Task marked as DONE." }
        format.json { head :ok }
      else
        format.html { redirect_to project_tasks_path, notice: "Error, unable to mark as done" }
        format.json { head :bad_request }
      end
    end
  end

  def destroy
    @task.destroy_and_notify(current_user, :participants)
    redirect_to project_tasks_path, notice: "Task was successfully destroyed."
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :due_date)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_form_id(task)
    "#{task.project.id}-#{task.id}"
  end
end

app/views/tasks/_form.html.erb
<%= form_for([project, task], url: url, html: { class: "form-stacked" }) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br/>
    <%= f.text_field :title, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br/>
    <%= f.date_field :due_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="grid-item form-box 3/5 medium-3/6 tablet-3/5 mobile-1/1 horizontal-center">
  <h2>Edit task</h2>

  <%= render "form",
    project: @task.project,
    task: @task,
    url: project_task_path(@task.project, @task) %>

  <%= link_to "Back",
    project_tasks_path(@task.project),
    class: "btn" %>
</div>

app/views/tasks/index.html.erb
<div class="grid-item form-box 4/5 medium-4/6 tablet-4/5 mobile-1/1 horizontal-center">

  <h1>Tasks in this project
    <a href="<%= new_project_task_path(@project) %>" class="icon-colored icon-btn">
      <i class="fa fa-plus-circle"></i>
    </a>
  </h1>

  <table class="table-hover table-headed">
    <thead>
      <tr>
        <th>Title</th>
        <th>Deadline</th>
        <th>Finished</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.due_date %></td>
          <td>
            <% if task.done %>
              <i class="fa fa-check-circle fa-lg icon-colored"></i>
            <% end %>
          </td>
          <td><%= link_to "Details", [task.project, task], class: "btn" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "Back", project_path(@project.id), class: "btn" %>
</div>

app/views/tasks/new.html.erb
<div class="grid-item form-box 3/5 medium-3/6 tablet-3/5 mobile-1/1 horizontal-center">
  <h2>Create new task</h2>

  <%= render "form",
    project: @task.project,
    task: @task,
    url: project_tasks_path(@task.project) %>

  <%= link_to "Back",
    project_tasks_path(@task.project),
    class: "btn" %>
</div>

app/views/tasks/show.html.erb
<div class="grid-item form-box 4/5 medium-3/6 tablet-3/5 mobile-1/1 horizontal-center">
  <table>
    <thead>
      <tr>
        <th colspan="2">
          <h3>Task details</h3>
        </th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><h4>Title</h4></td>
        <td><%= @task.title %></td>
      </tr>
      <tr>
        <td><h4>Description</h4></td>
        <td><%= @task.description %></td>
      </tr>
      <tr>
        <td><h4>Deadline</h4></td>
        <td><%= @task.due_date %></td>
      </tr>
      <tr>
        <td><h4>Status</h4></td>
        <td>
          <% if @task.done %>
            Finished
          <% else %>
            In progress
          <% end %>
        </td>
      </tr>
      <tr>
        <td><h4>Participants</h4></td>
        <td>
          <% if @task.participants.empty? %>
            No participants
          <% else %>
            <ul>
              <% @task.participants.each do |user| %>
                <li> <%= user.name %> <%= user.surname %></li>
              <% end %>
            </ul>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  <% unless @task.done %>
    <% if @task.participants.include?(current_user) %>
      <%= link_to "Leave task",
        {
          controller: :user_tasks,
          action: :leave ,
          project_id: @task.project.id,
          id: @task.id
        },
        method: :delete,
        data: { confirm: "Are you sure?" },
        class: "btn" %>
    <% else %>
      <%= link_to "Join task",
        {
          controller: :user_tasks,
          action: :assign ,
          project_id: @task.project.id,
          id: @task.id
        },
        method: :post,
        class: "btn" %>
    <% end %>

    <%= link_to "Edit",
    [:edit, @task.project, @task],
    class: "btn" %>

    <%= link_to "Mark as done",
      {
        controller: :tasks,
        action: :mark_as_done ,
        project_id: @task.project.id,
        id: @task.id
      },
      method: :put,
      data: { confirm: "Are you sure?" },
      class: "btn" %>
  <% end %>

  <%= link_to "Remove",
    [@task.project, @task],
    method: :delete,
    data: { confirm: "Are you sure?" },
    class: "btn" %>

  <%= link_to "Back",
    project_tasks_path(@task.project),
    class: "btn" %>
</div>