config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  get "/managed_projects" => "projects#managed_projects"
  get "/contributed_projects" => "projects#contributed_projects"

  resources :notifications, only: [:index] do
    member do
      put "mark_as_read"
    end
  end

  authenticated :user do
    root "users#dashboard"
  end

  get "/users/search" => "users#search"

  resources :projects do
    post "/create" => "user_projects#create"
    delete "/destroy" => "user_projects#destroy"
    get "/participants" => "user_projects#participants"
    member do
      get "link_contributors"
    end
    collection do
      get "managed"
      get "contributed"
    end
    resources :tasks
    post "/tasks/:id/assign" => "user_tasks#assign"
    delete "/tasks/:id/leave" => "user_tasks#leave"
    put "/tasks/:id/done" => "tasks#mark_as_done"
    resources :events
  end

  root "home#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notificable, polymorphic: true
  belongs_to :user

  scope :not_read, -> { where(read: false) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.incoming_notifications.not_read
  end

  def mark_as_read
    @notification = Notification.find(params[:id])
    if @notification.update_attribute(:read, true)
      redirect_to notifications_path
    else
      redirect_to root_path, notice: "Unable to update notification"
    end
  end
end

app/views/notifications/index.html.erb
<div class="container">
  <h2>My notifications: </h2>
  <% unless @notifications.empty? %>
    <% @notifications.each do |noti| %>
      <div class="grid grid-pair grid-middle">
        <div class="grid-item 1/2">
          <div class="box bg-silver notification-border">
            <%= noti.message %>
          </div>
        </div>
        <div class="grid-item 1/2 notification-btn">
          <%= link_to "Mark as read", mark_as_read_notification_path(noti), method: :put, class: "btn" %>
        </div>
      </div>
      <br>
    <% end %>
  <% else %>
      No new activity
  <% end %>
</div>