config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  get "/managed_projects" => "projects#managed_projects"
  get "/contributed_projects" => "projects#contributed_projects"

  resources :notifications, only: [:index] do
    member do
      put "mark_as_read"
    end
  end

  authenticated :user do
    root "users#dashboard"
  end

  get "/users/search" => "users#search"

  resources :projects do
    post "/create" => "user_projects#create"
    delete "/destroy" => "user_projects#destroy"
    get "/participants" => "user_projects#participants"
    member do
      get "link_contributors"
    end
    collection do
      get "managed"
      get "contributed"
    end
    resources :tasks
    post "/tasks/:id/assign" => "user_tasks#assign"
    delete "/tasks/:id/leave" => "user_tasks#leave"
    put "/tasks/:id/done" => "tasks#mark_as_done"
    resources :events
  end

  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :surname, presence: true

  has_many :managed_projects, class_name: "Project"
  has_many :user_projects
  has_many :contributed_projects, through: :user_projects, source: :project

  has_many :user_tasks
  has_many :assigned_tasks, through: :user_tasks, source: :task

  has_many :events, foreign_key: "author_id", dependent: :destroy

  has_many :incoming_notifications, class_name: "Notification"

  def takes_part_in_project?(project_id)
    projects.any? { |project| project.id == project_id }
  end

  def projects
    managed_projects + contributed_projects
  end

  def full_name
    "#{name} #{surname}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user_tasks = current_user.assigned_tasks.projects_with_not_done_tasks
    @contributed = []
    current_user.contributed_projects.each do |project|
      @contributed << project if project.user != current_user
    end
    @managed = current_user.managed_projects
  end

  def search
    @users = find_for_search(params[:name])
    @project = Project.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  private

  def find_for_search(param)
    find_name, find_surname = param.split(" ")
    if find_surname
      users = User.where("name like ? AND surname like ?",
        "#{find_name}%",
        "#{find_surname}%")
    else
      users = (
        User.where("name like ?", "#{find_name}%") +
        User.where("surname like ?", "#{find_name}%")).
        uniq
    end
    users
  end
end

app/views/users/_search_result.html.erb
<% users.each do |user| %>
  <div class="grid grid-middle">
    <div class="grid-item 1/10 mobile-1/5 my-padding">
      <%= link_to "+", project_create_path(project_id: @project.id, user_id: user.id), method: :post, class: "btn" %>
    </div>
    <div class="grid-item 9/10 mobile-4/5 my-padding">
      <%= user.name %> <%= user.surname %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="grid-pair">
  <div class="grid-item 1/4"><%= user.name %></div>
  <div class="grid-item 1/2"><%= user.surname %></div>
  <div class="grid-item 1/4">
     <%= link_to project_create_path(project, user), method: :post %>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="dashboard grid grid-center">
  <main class="grid-item 2/3 mobile-1/1">
    <h2>Your tasks</h2>

    <ul>
    <% @user_tasks.each do |project, tasks| %>
      <h3><%= project.title %></h3>

      <% tasks.each do |task| %>
        <li class="task-item">
          <%= check_box_tag task_form_id(task), nil, task.done %>
          <%= label_tag task_form_id(task), task.title, class: "task-title" %>

          <i class="fa fa-caret-down"></i>

          <div class="task-due-date">
            <%= "to #{task.due_date.to_formatted_s(:short)}" %>
          </div>

          <div class="task-extra hidden">
            <p><%= task.description %></p>
          </div>
        </li>
      <% end %>
    <% end %>
    </ul>
  </main>

  <aside class="grid-item 1/3 mobile-1/1">
    <h2>Projects</h2>
    <ul class="list-menu">
    <h3>Managed</h3>
    <% @managed.each do |project| %>
      <li>
        <%= link_to project.title, project_tasks_path(project) %>
      </li>
    <% end %>
    </ul>
    <ul class="list-menu">
    <h3>Contributed</h3>
    <% @contributed.each do |project| %>
      <li>
        <%= link_to project.title, project_tasks_path(project) %>
      </li>
    <% end %>
    </ul>
  </main>
</div>

app/views/users/search.js.erb
$('#search-result').html("<%= j (render partial: 'users/search_result.html.erb', locals: { users: @users, project: @project } ) %>");