config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  get "/managed_projects" => "projects#managed_projects"
  get "/contributed_projects" => "projects#contributed_projects"

  resources :notifications, only: [:index] do
    member do
      put "mark_as_read"
    end
  end

  authenticated :user do
    root "users#dashboard"
  end

  get "/users/search" => "users#search"

  resources :projects do
    post "/create" => "user_projects#create"
    delete "/destroy" => "user_projects#destroy"
    get "/participants" => "user_projects#participants"
    member do
      get "link_contributors"
    end
    collection do
      get "managed"
      get "contributed"
    end
    resources :tasks
    post "/tasks/:id/assign" => "user_tasks#assign"
    delete "/tasks/:id/leave" => "user_tasks#leave"
    put "/tasks/:id/done" => "tasks#mark_as_done"
    resources :events
  end

  root "home#index"
end

app/models/project.rb
class Project < ApplicationRecord
  include NotificationMethods

  validates :title, :date, :description, presence: true
  validates :date, future_date: true

  belongs_to :user
  has_many :user_projects, dependent: :destroy
  has_many :contributors, through: :user_projects, source: :user

  has_many :events, dependent: :destroy

  has_many :tasks, dependent: :destroy

  has_many :notifications, as: :notificable

  def create_project(current_user)
    transaction do
      begin
        UserProject.create!(user: current_user, project: self)
        self.save!
      rescue
        false
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy, :link_contributors]
  before_action only: [:edit, :update, :destroy, :link_contributors] { authorize @project, :modify? }
  before_action only: [:show] { authorize @project, :access? }

  def index
   @contributed = []
    current_user.contributed_projects.each do |project|
      @contributed << project if project.user != current_user
    end
    @managed = current_user.managed_projects
  end

  def managed
    @projects = current_user.managed_projects.all
  end

  def contributed
    @projects = []
    current_user.contributed_projects.each do |project|
      @projects << project if project.user != current_user
    end
  end

  def show
  end

  def new
    @project = current_user.managed_projects.new
  end

  def create
    @project = current_user.managed_projects.new(project_params)
    if @project.create_project(current_user)
      redirect_to @project, notice: "Poject was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update_and_notify(project_params, current_user, :contributors)
      redirect_to @project, notice: "Poject was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @project.destroy_and_notify(current_user, :contributors)
    redirect_to projects_url, notice: "Poject was successfully destroyed."
  end

  def link_contributors
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :date)
  end
end

app/views/projects/_form.html.erb
<%= form_for([project], html: { class: "form-stacked" }) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br/>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="grid-item form-box 3/5 medium-3/6 tablet-3/5 mobile-1/1 horizontal-center">
  <h2>Edit project</h2>
  <%= render "form",  project: @project %>

  <%= link_to "Back", projects_path, class: "btn" %>
</div>

app/views/projects/index.html.erb
<div class="grid-item form-box 4/5 medium-4/6 tablet-4/5 mobile-1/1 horizontal-center">

  <h1>Projects
    <a href="<%= new_project_path %>" class="icon-colored icon-btn">
      <i class="fa fa-plus-circle"></i>
    </a>
  </h1>

  <% if !@managed.empty? %>
    <table class="table-hover table-headed">
      <thead>
        <td><h3>Managed</h3></td>
      </thead>
      <tbody>
        <% @managed.each do |project| %>
          <tr>
            <td><%= project.title %></td>
            <td><%= link_to "Details", project, class: "btn" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <% if !@contributed.empty? %>
    <table class="table-hover table-headed">
      <thead>
        <td><h3>Contributed</h3></td>
      </thead>
      <tbody>
        <% @contributed.each do |project| %>
          <tr>
            <td><%= project.title %></td>
            <td><%= link_to "Details", project, class: "btn" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/projects/link_contributors.html.erb
<% if policy(@project).modify? %>
  <h3>Add user to the project:</h3>

  <div class="search-user">
    <%= form_tag( users_search_path, method: :get, remote: true ) do %>
      <div class="grid grid-bottom">
        <div class="grid-item 2/3">
          <%= label_tag "name", "Search for a user:" %>
          <%= text_field_tag "name" %>
          <%= hidden_field_tag "id", @project.id %>
        </div>
        <div class="grid-item 1/3">
          <%= submit_tag("Search") %>
        </div>
      </div>
    <% end %>

    <div id="search-result"></div>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class="grid-item form-box 3/5 medium-3/6 tablet-3/5 mobile-1/1 horizontal-center">
  <h2>Create new project</h2>

  <%= render "form", project: @project %>

  <%= link_to "Back", projects_path, class: "btn" %>
</div>

app/views/projects/show.html.erb
<div class="grid-item form-box 4/5 medium-3/6 tablet-3/5 mobile-1/1 horizontal-center">
  <table>
    <thead>
      <tr>
        <th colspan="2">
          <h3>Project details</h3>
        </th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><h4>Title</h4></td>
        <td><%= @project.title %></td>
      </tr>
      <tr>
        <td><h4>Description</h4></td>
        <td><%= @project.description %></td>
      </tr>
      <tr>
        <td><h4>Date</h4></td>
        <td><%= @project.date.strftime("%d/%m/%Y") %></td>
      </tr>
      <tr>     
    </tbody>
  </table>

  <% if policy(@project).modify? %>
    <%= link_to "Edit", edit_project_path(@project), class: "btn" %>
  <% end %>
  <%= link_to "Back", projects_path, class: "btn" %>
  <%= link_to "All tasks", project_tasks_path(@project), class: "btn" %>
  <%= link_to "All events", project_events_path(@project), class: "btn" %>
  <%= link_to "Participants", project_participants_path(@project), class: "btn" %>
</div>